name: Gone to the Dogs
favicon: null
layout_spectrum: 0.7181646060198545
typography_spectrum: 0.5489008468575776
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.6691421968862414
  lightness: 0.5363921909593046
  saturation: 0.060558169381693006
  rhythmicContrast: 0.8077330875676125
purpose: []
