name: Gone to the Dogs
favicon: null
layout_spectrum: 0.85397
typography_spectrum: 0.68625
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 1
  lightness: 0.8125
  saturation: 0.625
  rhythmicContrast: 0.75
purpose: []
